import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import TopNav from "@/components/topNav";
import Footer from "@/components/footer";
import { AppProvider } from "@/components/context";
import Logo from "@/components/logo";
import QuickActions from "@/components/quickActions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kojo Herbie",
  description: "Generated by create next app",
  icons: {
    icon: "./icon.ico",
    sizes: '50x50',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Logo/>
          <QuickActions/>
          <TopNav/> {children}<Footer/>
        </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
